// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (id, user_id, filename, content_type, size_bytes, storage_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, filename, content_type, size_bytes, storage_path, created_at
`

type CreateAttachmentParams struct {
	ID          uuid.UUID
	UserID      int32
	Filename    string
	ContentType string
	SizeBytes   int64
	StoragePath string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (*Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StoragePath,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteAttachment = `-- name: DeleteAttachment :one
DELETE FROM attachments
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, filename, content_type, size_bytes, storage_path, created_at
`

type DeleteAttachmentParams struct {
	ID     uuid.UUID
	UserID int32
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (*Attachment, error) {
	row := q.db.QueryRow(ctx, deleteAttachment, arg.ID, arg.UserID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return &i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, user_id, filename, content_type, size_bytes, storage_path, created_at
FROM attachments
WHERE id = $1 AND user_id = $2
`

type GetAttachmentByIDParams struct {
	ID     uuid.UUID
	UserID int32
}

func (q *Queries) GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (*Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, arg.ID, arg.UserID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return &i, err
}
