// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachment_links.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const createAttachmentLink = `-- name: CreateAttachmentLink :exec
INSERT INTO attachment_links (attachment_id, user_id, resource_type, resource_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type CreateAttachmentLinkParams struct {
	AttachmentID uuid.UUID
	UserID       int32
	ResourceType string
	ResourceID   uuid.UUID
}

func (q *Queries) CreateAttachmentLink(ctx context.Context, arg CreateAttachmentLinkParams) error {
	_, err := q.db.Exec(ctx, createAttachmentLink,
		arg.AttachmentID,
		arg.UserID,
		arg.ResourceType,
		arg.ResourceID,
	)
	return err
}

const deleteAttachmentLink = `-- name: DeleteAttachmentLink :exec
DELETE FROM attachment_links
WHERE attachment_id = $1
  AND user_id = $2
  AND resource_type = $3
  AND resource_id = $4
`

type DeleteAttachmentLinkParams struct {
	AttachmentID uuid.UUID
	UserID       int32
	ResourceType string
	ResourceID   uuid.UUID
}

func (q *Queries) DeleteAttachmentLink(ctx context.Context, arg DeleteAttachmentLinkParams) error {
	_, err := q.db.Exec(ctx, deleteAttachmentLink,
		arg.AttachmentID,
		arg.UserID,
		arg.ResourceType,
		arg.ResourceID,
	)
	return err
}

const listAttachmentsByResource = `-- name: ListAttachmentsByResource :many
SELECT a.id, a.user_id, a.filename, a.content_type, a.size_bytes, a.storage_path, a.created_at
FROM attachment_links l
JOIN attachments a ON a.id = l.attachment_id
WHERE l.user_id = $1
  AND l.resource_type = $2
  AND l.resource_id = $3
ORDER BY l.created_at DESC
`

type ListAttachmentsByResourceParams struct {
	UserID       int32
	ResourceType string
	ResourceID   uuid.UUID
}

func (q *Queries) ListAttachmentsByResource(ctx context.Context, arg ListAttachmentsByResourceParams) ([]*Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByResource, arg.UserID, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
