// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_codes.sql

package querier

import (
	"context"
	"time"
)

const approveDeviceCode = `-- name: ApproveDeviceCode :one
UPDATE device_codes
SET status = 'approved',
    user_id = $2,
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, device_code_hash, user_code_hash, client_id, scope, status, user_id, created_at, updated_at, expires_at, last_poll_at, poll_interval_sec, poll_count, ip, user_agent
`

type ApproveDeviceCodeParams struct {
	ID     int64
	UserID *int32
}

func (q *Queries) ApproveDeviceCode(ctx context.Context, arg ApproveDeviceCodeParams) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, approveDeviceCode, arg.ID, arg.UserID)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.Scope,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastPollAt,
		&i.PollIntervalSec,
		&i.PollCount,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const consumeDeviceCodeIfApproved = `-- name: ConsumeDeviceCodeIfApproved :one
UPDATE device_codes
SET status = 'consumed',
    updated_at = now()
WHERE id = $1
  AND status = 'approved'
RETURNING id, device_code_hash, user_code_hash, client_id, scope, status, user_id, created_at, updated_at, expires_at, last_poll_at, poll_interval_sec, poll_count, ip, user_agent
`

func (q *Queries) ConsumeDeviceCodeIfApproved(ctx context.Context, id int64) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, consumeDeviceCodeIfApproved, id)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.Scope,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastPollAt,
		&i.PollIntervalSec,
		&i.PollCount,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const createDeviceCode = `-- name: CreateDeviceCode :one
INSERT INTO device_codes (
  device_code_hash,
  user_code_hash,
  client_id,
  scope,
  status,
  user_id,
  expires_at,
  poll_interval_sec,
  ip,
  user_agent
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8, $9, $10
)
RETURNING id, device_code_hash, user_code_hash, client_id, scope, status, user_id, created_at, updated_at, expires_at, last_poll_at, poll_interval_sec, poll_count, ip, user_agent
`

type CreateDeviceCodeParams struct {
	DeviceCodeHash  []byte
	UserCodeHash    []byte
	ClientID        string
	Scope           *string
	Status          string
	UserID          *int32
	ExpiresAt       time.Time
	PollIntervalSec int32
	Ip              *string
	UserAgent       *string
}

func (q *Queries) CreateDeviceCode(ctx context.Context, arg CreateDeviceCodeParams) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, createDeviceCode,
		arg.DeviceCodeHash,
		arg.UserCodeHash,
		arg.ClientID,
		arg.Scope,
		arg.Status,
		arg.UserID,
		arg.ExpiresAt,
		arg.PollIntervalSec,
		arg.Ip,
		arg.UserAgent,
	)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.Scope,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastPollAt,
		&i.PollIntervalSec,
		&i.PollCount,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const expireDeviceCodes = `-- name: ExpireDeviceCodes :exec
UPDATE device_codes
SET status = 'expired',
    updated_at = now()
WHERE status IN ('pending', 'approved')
  AND expires_at <= now()
`

func (q *Queries) ExpireDeviceCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireDeviceCodes)
	return err
}

const getDeviceCodeByDeviceHash = `-- name: GetDeviceCodeByDeviceHash :one
SELECT id, device_code_hash, user_code_hash, client_id, scope, status, user_id, created_at, updated_at, expires_at, last_poll_at, poll_interval_sec, poll_count, ip, user_agent FROM device_codes
WHERE device_code_hash = $1
LIMIT 1
`

func (q *Queries) GetDeviceCodeByDeviceHash(ctx context.Context, deviceCodeHash []byte) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeByDeviceHash, deviceCodeHash)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.Scope,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastPollAt,
		&i.PollIntervalSec,
		&i.PollCount,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const getDeviceCodeByUserHash = `-- name: GetDeviceCodeByUserHash :one
SELECT id, device_code_hash, user_code_hash, client_id, scope, status, user_id, created_at, updated_at, expires_at, last_poll_at, poll_interval_sec, poll_count, ip, user_agent FROM device_codes
WHERE user_code_hash = $1
LIMIT 1
`

func (q *Queries) GetDeviceCodeByUserHash(ctx context.Context, userCodeHash []byte) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeByUserHash, userCodeHash)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.Scope,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastPollAt,
		&i.PollIntervalSec,
		&i.PollCount,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const markDeviceCodeConsumed = `-- name: MarkDeviceCodeConsumed :one
UPDATE device_codes
SET status = 'consumed',
    updated_at = now()
WHERE id = $1
RETURNING id, device_code_hash, user_code_hash, client_id, scope, status, user_id, created_at, updated_at, expires_at, last_poll_at, poll_interval_sec, poll_count, ip, user_agent
`

func (q *Queries) MarkDeviceCodeConsumed(ctx context.Context, id int64) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, markDeviceCodeConsumed, id)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.Scope,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastPollAt,
		&i.PollIntervalSec,
		&i.PollCount,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const touchDeviceCodePoll = `-- name: TouchDeviceCodePoll :one
UPDATE device_codes
SET last_poll_at = now(),
    poll_count = poll_count + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, device_code_hash, user_code_hash, client_id, scope, status, user_id, created_at, updated_at, expires_at, last_poll_at, poll_interval_sec, poll_count, ip, user_agent
`

func (q *Queries) TouchDeviceCodePoll(ctx context.Context, id int64) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, touchDeviceCodePoll, id)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.Scope,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastPollAt,
		&i.PollIntervalSec,
		&i.PollCount,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}

const updateDeviceCodeStatus = `-- name: UpdateDeviceCodeStatus :one
UPDATE device_codes
SET status = $2,
    user_id = COALESCE($3, user_id),
    updated_at = now()
WHERE id = $1
RETURNING id, device_code_hash, user_code_hash, client_id, scope, status, user_id, created_at, updated_at, expires_at, last_poll_at, poll_interval_sec, poll_count, ip, user_agent
`

type UpdateDeviceCodeStatusParams struct {
	ID     int64
	Status string
	UserID *int32
}

func (q *Queries) UpdateDeviceCodeStatus(ctx context.Context, arg UpdateDeviceCodeStatusParams) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, updateDeviceCodeStatus, arg.ID, arg.Status, arg.UserID)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.ClientID,
		&i.Scope,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastPollAt,
		&i.PollIntervalSec,
		&i.PollCount,
		&i.Ip,
		&i.UserAgent,
	)
	return &i, err
}
