// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memo_tags.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const createMemoTag = `-- name: CreateMemoTag :exec
INSERT INTO memo_tags (memo_id, user_id, tag)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type CreateMemoTagParams struct {
	MemoID uuid.UUID
	UserID int32
	Tag    string
}

func (q *Queries) CreateMemoTag(ctx context.Context, arg CreateMemoTagParams) error {
	_, err := q.db.Exec(ctx, createMemoTag, arg.MemoID, arg.UserID, arg.Tag)
	return err
}

const deleteMemoTagsByMemo = `-- name: DeleteMemoTagsByMemo :exec
DELETE FROM memo_tags
WHERE memo_id = $1 AND user_id = $2
`

type DeleteMemoTagsByMemoParams struct {
	MemoID uuid.UUID
	UserID int32
}

func (q *Queries) DeleteMemoTagsByMemo(ctx context.Context, arg DeleteMemoTagsByMemoParams) error {
	_, err := q.db.Exec(ctx, deleteMemoTagsByMemo, arg.MemoID, arg.UserID)
	return err
}

const listMemoTagsByMemo = `-- name: ListMemoTagsByMemo :many
SELECT tag
FROM memo_tags
WHERE memo_id = $1 AND user_id = $2
ORDER BY tag ASC
`

type ListMemoTagsByMemoParams struct {
	MemoID uuid.UUID
	UserID int32
}

func (q *Queries) ListMemoTagsByMemo(ctx context.Context, arg ListMemoTagsByMemoParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listMemoTagsByMemo, arg.MemoID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT tag AS name, COUNT(*)::bigint AS count
FROM memo_tags
WHERE user_id = $1
  AND ($2::text = '' OR tag ILIKE '%' || $2 || '%')
GROUP BY tag
ORDER BY count DESC, name ASC
LIMIT $3 OFFSET $4
`

type ListTagsParams struct {
	UserID  int32
	Column2 string
	Limit   int32
	Offset  int32
}

type ListTagsRow struct {
	Name  string
	Count int64
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]*ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
