// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memo_relations.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const createMemoRelation = `-- name: CreateMemoRelation :exec
INSERT INTO memo_relations (source_memo_id, target_memo_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type CreateMemoRelationParams struct {
	SourceMemoID uuid.UUID
	TargetMemoID uuid.UUID
	UserID       int32
}

func (q *Queries) CreateMemoRelation(ctx context.Context, arg CreateMemoRelationParams) error {
	_, err := q.db.Exec(ctx, createMemoRelation, arg.SourceMemoID, arg.TargetMemoID, arg.UserID)
	return err
}

const deleteMemoRelationsBySource = `-- name: DeleteMemoRelationsBySource :exec
DELETE FROM memo_relations
WHERE source_memo_id = $1 AND user_id = $2
`

type DeleteMemoRelationsBySourceParams struct {
	SourceMemoID uuid.UUID
	UserID       int32
}

func (q *Queries) DeleteMemoRelationsBySource(ctx context.Context, arg DeleteMemoRelationsBySourceParams) error {
	_, err := q.db.Exec(ctx, deleteMemoRelationsBySource, arg.SourceMemoID, arg.UserID)
	return err
}

const listMemoReferenceIDsBySource = `-- name: ListMemoReferenceIDsBySource :many
SELECT target_memo_id
FROM memo_relations
WHERE source_memo_id = $1 AND user_id = $2
ORDER BY target_memo_id ASC
`

type ListMemoReferenceIDsBySourceParams struct {
	SourceMemoID uuid.UUID
	UserID       int32
}

func (q *Queries) ListMemoReferenceIDsBySource(ctx context.Context, arg ListMemoReferenceIDsBySourceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMemoReferenceIDsBySource, arg.SourceMemoID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var target_memo_id uuid.UUID
		if err := rows.Scan(&target_memo_id); err != nil {
			return nil, err
		}
		items = append(items, target_memo_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
