// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memos.sql

package querier

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMemo = `-- name: CreateMemo :one
INSERT INTO memos (id, user_id, content, excerpt, state, archived_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, content, excerpt, state, archived_at, created_at, updated_at
`

type CreateMemoParams struct {
	ID         uuid.UUID
	UserID     int32
	Content    string
	Excerpt    string
	State      string
	ArchivedAt *time.Time
}

func (q *Queries) CreateMemo(ctx context.Context, arg CreateMemoParams) (*Memo, error) {
	row := q.db.QueryRow(ctx, createMemo,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.Excerpt,
		arg.State,
		arg.ArchivedAt,
	)
	var i Memo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Excerpt,
		&i.State,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteMemo = `-- name: DeleteMemo :one
DELETE FROM memos
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteMemoParams struct {
	ID     uuid.UUID
	UserID int32
}

func (q *Queries) DeleteMemo(ctx context.Context, arg DeleteMemoParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteMemo, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMemoByID = `-- name: GetMemoByID :one
SELECT id, user_id, content, excerpt, state, archived_at, created_at, updated_at
FROM memos
WHERE id = $1 AND user_id = $2
`

type GetMemoByIDParams struct {
	ID     uuid.UUID
	UserID int32
}

func (q *Queries) GetMemoByID(ctx context.Context, arg GetMemoByIDParams) (*Memo, error) {
	row := q.db.QueryRow(ctx, getMemoByID, arg.ID, arg.UserID)
	var i Memo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Excerpt,
		&i.State,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listMemoBacklinks = `-- name: ListMemoBacklinks :many
SELECT m.id, m.user_id, m.content, m.excerpt, m.state, m.archived_at, m.created_at, m.updated_at
FROM memo_relations r
JOIN memos m ON m.id = r.source_memo_id AND m.user_id = r.user_id
WHERE r.user_id = $1 AND r.target_memo_id = $2
ORDER BY m.updated_at DESC, m.id DESC
`

type ListMemoBacklinksParams struct {
	UserID       int32
	TargetMemoID uuid.UUID
}

func (q *Queries) ListMemoBacklinks(ctx context.Context, arg ListMemoBacklinksParams) ([]*Memo, error) {
	rows, err := q.db.Query(ctx, listMemoBacklinks, arg.UserID, arg.TargetMemoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Memo
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Excerpt,
			&i.State,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemos = `-- name: ListMemos :many
SELECT id, user_id, content, excerpt, state, archived_at, created_at, updated_at
FROM memos m
WHERE m.user_id = $1
  AND ($2::text = '' OR m.state = $2)
  AND ($3::text = '' OR m.content ILIKE '%' || $3 || '%' OR m.excerpt ILIKE '%' || $3 || '%')
  AND (
    $4::text = ''
    OR EXISTS (
      SELECT 1
      FROM memo_tags mt
      WHERE mt.memo_id = m.id
        AND mt.user_id = m.user_id
        AND mt.tag = $4
    )
  )
ORDER BY m.updated_at DESC, m.id DESC
LIMIT $5 OFFSET $6
`

type ListMemosParams struct {
	UserID  int32
	Column2 string
	Column3 string
	Column4 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListMemos(ctx context.Context, arg ListMemosParams) ([]*Memo, error) {
	rows, err := q.db.Query(ctx, listMemos,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Memo
	for rows.Next() {
		var i Memo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Excerpt,
			&i.State,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemo = `-- name: UpdateMemo :one
UPDATE memos
SET content = $3,
    excerpt = $4,
    state = $5,
    archived_at = $6,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, content, excerpt, state, archived_at, created_at, updated_at
`

type UpdateMemoParams struct {
	ID         uuid.UUID
	UserID     int32
	Content    string
	Excerpt    string
	State      string
	ArchivedAt *time.Time
}

func (q *Queries) UpdateMemo(ctx context.Context, arg UpdateMemoParams) (*Memo, error) {
	row := q.db.QueryRow(ctx, updateMemo,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.Excerpt,
		arg.State,
		arg.ArchivedAt,
	)
	var i Memo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Excerpt,
		&i.State,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
