// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          uuid.UUID
	UserID      int32
	Filename    string
	ContentType string
	SizeBytes   int64
	StoragePath string
	CreatedAt   time.Time
}

type AttachmentLink struct {
	AttachmentID uuid.UUID
	UserID       int32
	ResourceType string
	ResourceID   uuid.UUID
	CreatedAt    time.Time
}

type Counter struct {
	ID    int32
	Value int32
}

type TodoItem struct {
	ID             uuid.UUID
	UserID         int32
	Title          string
	Done           bool
	CreatedAt      time.Time
	Bucket         string
	PlannedForDay  pgtype.Date
	PlannedForWeek pgtype.Date
	Description    string
}

type User struct {
	ID        int32
	CreatedAt time.Time
}
