// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          uuid.UUID
	UserID      int32
	Filename    string
	ContentType string
	SizeBytes   int64
	StoragePath string
	CreatedAt   time.Time
}

type AttachmentLink struct {
	AttachmentID uuid.UUID
	UserID       int32
	ResourceType string
	ResourceID   uuid.UUID
	CreatedAt    time.Time
}

type Counter struct {
	ID    int32
	Value int32
}

type DeviceCode struct {
	ID              int64
	DeviceCodeHash  []byte
	UserCodeHash    []byte
	ClientID        string
	Scope           *string
	Status          string
	UserID          *int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ExpiresAt       time.Time
	LastPollAt      *time.Time
	PollIntervalSec int32
	PollCount       int32
	Ip              *string
	UserAgent       *string
}

type Memo struct {
	ID         uuid.UUID
	UserID     int32
	Content    json.RawMessage
	Excerpt    string
	State      string
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	PlainText  string
}

type MemoRelation struct {
	SourceMemoID uuid.UUID
	TargetMemoID uuid.UUID
	UserID       int32
}

type MemoTag struct {
	MemoID uuid.UUID
	UserID int32
	Tag    string
}

type TodoItem struct {
	ID             uuid.UUID
	UserID         int32
	Title          string
	Done           bool
	CreatedAt      time.Time
	Bucket         string
	PlannedForDay  pgtype.Date
	PlannedForWeek pgtype.Date
	Description    string
	DoneAt         *time.Time
}

type User struct {
	ID        int32
	CreatedAt time.Time
}
