// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (*Attachment, error)
	CreateAttachmentLink(ctx context.Context, arg CreateAttachmentLinkParams) error
	CreateMemo(ctx context.Context, arg CreateMemoParams) (*CreateMemoRow, error)
	CreateMemoRelation(ctx context.Context, arg CreateMemoRelationParams) error
	CreateMemoTag(ctx context.Context, arg CreateMemoTagParams) error
	CreateTodo(ctx context.Context, arg CreateTodoParams) (*TodoItem, error)
	DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (*Attachment, error)
	DeleteAttachmentLink(ctx context.Context, arg DeleteAttachmentLinkParams) error
	DeleteAttachmentLinksByResource(ctx context.Context, arg DeleteAttachmentLinksByResourceParams) error
	DeleteMemo(ctx context.Context, arg DeleteMemoParams) (uuid.UUID, error)
	DeleteMemoRelationsBySource(ctx context.Context, arg DeleteMemoRelationsBySourceParams) error
	DeleteMemoTagsByMemo(ctx context.Context, arg DeleteMemoTagsByMemoParams) error
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) (uuid.UUID, error)
	EnsureUser(ctx context.Context, id int32) error
	GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (*Attachment, error)
	GetCounter(ctx context.Context) (*Counter, error)
	GetMemoByID(ctx context.Context, arg GetMemoByIDParams) (*GetMemoByIDRow, error)
	IncrementCounter(ctx context.Context) error
	ListAttachmentsByResource(ctx context.Context, arg ListAttachmentsByResourceParams) ([]*Attachment, error)
	ListMemoBacklinks(ctx context.Context, arg ListMemoBacklinksParams) ([]*ListMemoBacklinksRow, error)
	ListMemoReferenceIDsBySource(ctx context.Context, arg ListMemoReferenceIDsBySourceParams) ([]uuid.UUID, error)
	ListMemoTagsByMemo(ctx context.Context, arg ListMemoTagsByMemoParams) ([]string, error)
	ListMemos(ctx context.Context, arg ListMemosParams) ([]*ListMemosRow, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]*ListTagsRow, error)
	ListTodosByUser(ctx context.Context, userID int32) ([]*TodoItem, error)
	NormalizeTodayToWeek(ctx context.Context, userID int32) error
	NormalizeWeekToLater(ctx context.Context, userID int32) error
	UpdateMemo(ctx context.Context, arg UpdateMemoParams) (*UpdateMemoRow, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (*TodoItem, error)
	UpdateTodoBucket(ctx context.Context, arg UpdateTodoBucketParams) error
}

var _ Querier = (*Queries)(nil)
