// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo.sql

package querier

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todo_items (id, user_id, title, bucket)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, done, created_at, done_at, bucket, planned_for_day, planned_for_week, description
`

type CreateTodoParams struct {
	ID     uuid.UUID
	UserID int32
	Title  string
	Bucket string
}

type CreateTodoRow struct {
	ID             uuid.UUID
	UserID         int32
	Title          string
	Done           bool
	CreatedAt      time.Time
	DoneAt         *time.Time
	Bucket         string
	PlannedForDay  pgtype.Date
	PlannedForWeek pgtype.Date
	Description    string
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (*CreateTodoRow, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Bucket,
	)
	var i CreateTodoRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
		&i.DoneAt,
		&i.Bucket,
		&i.PlannedForDay,
		&i.PlannedForWeek,
		&i.Description,
	)
	return &i, err
}

const deleteTodo = `-- name: DeleteTodo :one
DELETE FROM todo_items
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteTodoParams struct {
	ID     uuid.UUID
	UserID int32
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteTodo, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listTodosByUser = `-- name: ListTodosByUser :many
SELECT id, user_id, title, done, created_at, done_at, bucket, planned_for_day, planned_for_week, description
FROM todo_items
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListTodosByUserRow struct {
	ID             uuid.UUID
	UserID         int32
	Title          string
	Done           bool
	CreatedAt      time.Time
	DoneAt         *time.Time
	Bucket         string
	PlannedForDay  pgtype.Date
	PlannedForWeek pgtype.Date
	Description    string
}

func (q *Queries) ListTodosByUser(ctx context.Context, userID int32) ([]*ListTodosByUserRow, error) {
	rows, err := q.db.Query(ctx, listTodosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTodosByUserRow
	for rows.Next() {
		var i ListTodosByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Done,
			&i.CreatedAt,
			&i.DoneAt,
			&i.Bucket,
			&i.PlannedForDay,
			&i.PlannedForWeek,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const normalizeTodayToWeek = `-- name: NormalizeTodayToWeek :exec
UPDATE todo_items
SET bucket = 'week',
    planned_for_day = NULL
WHERE user_id = $1
  AND bucket = 'today'
  AND done = FALSE
  AND planned_for_day IS NOT NULL
  AND planned_for_day < CURRENT_DATE
`

func (q *Queries) NormalizeTodayToWeek(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, normalizeTodayToWeek, userID)
	return err
}

const normalizeWeekToLater = `-- name: NormalizeWeekToLater :exec
UPDATE todo_items
SET bucket = 'later',
    planned_for_week = NULL
WHERE user_id = $1
  AND bucket = 'week'
  AND done = FALSE
  AND planned_for_week IS NOT NULL
  AND planned_for_week < date_trunc('week', CURRENT_DATE)::DATE
`

func (q *Queries) NormalizeWeekToLater(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, normalizeWeekToLater, userID)
	return err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todo_items
SET title = $3,
    done = $4,
    done_at = $5,
    description = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, done, created_at, done_at, bucket, planned_for_day, planned_for_week, description
`

type UpdateTodoParams struct {
	ID          uuid.UUID
	UserID      int32
	Title       string
	Done        bool
	DoneAt      *time.Time
	Description string
}

type UpdateTodoRow struct {
	ID             uuid.UUID
	UserID         int32
	Title          string
	Done           bool
	CreatedAt      time.Time
	DoneAt         *time.Time
	Bucket         string
	PlannedForDay  pgtype.Date
	PlannedForWeek pgtype.Date
	Description    string
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (*UpdateTodoRow, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Done,
		arg.DoneAt,
		arg.Description,
	)
	var i UpdateTodoRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
		&i.DoneAt,
		&i.Bucket,
		&i.PlannedForDay,
		&i.PlannedForWeek,
		&i.Description,
	)
	return &i, err
}

const updateTodoBucket = `-- name: UpdateTodoBucket :exec
UPDATE todo_items
SET bucket = $3,
    planned_for_day = $4,
    planned_for_week = $5
WHERE id = $1 AND user_id = $2
`

type UpdateTodoBucketParams struct {
	ID             uuid.UUID
	UserID         int32
	Bucket         string
	PlannedForDay  pgtype.Date
	PlannedForWeek pgtype.Date
}

func (q *Queries) UpdateTodoBucket(ctx context.Context, arg UpdateTodoBucketParams) error {
	_, err := q.db.Exec(ctx, updateTodoBucket,
		arg.ID,
		arg.UserID,
		arg.Bucket,
		arg.PlannedForDay,
		arg.PlannedForWeek,
	)
	return err
}
