// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package querier

import (
	"context"
)

const ensureUser = `-- name: EnsureUser :exec
INSERT INTO users (id)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, ensureUser, id)
	return err
}
