// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/cloudcarver/anclax DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/gofiber/fiber/v3"
	"github.com/google/uuid"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for MemoState.
const (
	MemoStateActive   MemoState = "active"
	MemoStateArchived MemoState = "archived"
)

// Defines values for TodoItemBucket.
const (
	TodoItemBucketLater TodoItemBucket = "later"
	TodoItemBucketWeek  TodoItemBucket = "week"
	TodoItemBucketToday TodoItemBucket = "today"
)

// Defines values for UpdateTodoRequestBucket.
const (
	UpdateTodoRequestBucketLater UpdateTodoRequestBucket = "later"
	UpdateTodoRequestBucketWeek  UpdateTodoRequestBucket = "week"
	UpdateTodoRequestBucketToday UpdateTodoRequestBucket = "today"
)

// Attachment defines model for Attachment.
type Attachment struct {
	ContentType string    `json:"contentType"`
	CreatedAt   time.Time `json:"createdAt"`
	DownloadUrl string    `json:"downloadUrl"`
	Filename    string    `json:"filename"`
	Id          uuid.UUID `json:"id"`
	SizeBytes   int64     `json:"sizeBytes"`
}

// Counter defines model for Counter.
type Counter struct {
	Count int32 `json:"count"`
}

// CreateMemoRequest defines model for CreateMemoRequest.
type CreateMemoRequest struct {
	Content    MemoContent `json:"content"`
	Excerpt    string      `json:"excerpt"`
	PlainText  string      `json:"plainText"`
	References []uuid.UUID `json:"references"`
	Tags       []string    `json:"tags"`
}

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Title string `json:"title"`
}

// LinkAttachmentRequest defines model for LinkAttachmentRequest.
type LinkAttachmentRequest struct {
	ResourceId   uuid.UUID `json:"resourceId"`
	ResourceType string    `json:"resourceType"`
}

// Memo defines model for Memo.
type Memo struct {
	ArchivedAt *time.Time  `json:"archivedAt,omitempty"`
	Content    MemoContent `json:"content"`
	CreatedAt  time.Time   `json:"createdAt"`
	Excerpt    string      `json:"excerpt"`
	Id         uuid.UUID   `json:"id"`
	PlainText  string      `json:"plainText"`
	References []uuid.UUID `json:"references"`
	State      MemoState   `json:"state"`
	Tags       []string    `json:"tags"`
	UpdatedAt  time.Time   `json:"updatedAt"`
}

// MemoContent defines model for MemoContent.
type MemoContent struct {
}

// MemoSummary defines model for MemoSummary.
type MemoSummary struct {
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
	Excerpt    string     `json:"excerpt"`
	Id         uuid.UUID  `json:"id"`
	PlainText  string     `json:"plainText"`
	State      MemoState  `json:"state"`
	Tags       []string   `json:"tags"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}

// TagSummary defines model for TagSummary.
type TagSummary struct {
	Count int64  `json:"count"`
	Name  string `json:"name"`
}

// TodoItem defines model for TodoItem.
type TodoItem struct {
	Bucket      TodoItemBucket `json:"bucket"`
	CreatedAt   time.Time      `json:"createdAt"`
	Description string         `json:"description"`
	Done        bool           `json:"done"`
	Id          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
}

// UpdateMemoRequest defines model for UpdateMemoRequest.
type UpdateMemoRequest struct {
	Content    MemoContent `json:"content"`
	Excerpt    string      `json:"excerpt"`
	PlainText  string      `json:"plainText"`
	References []uuid.UUID `json:"references"`
	State      *MemoState  `json:"state,omitempty"`
	Tags       []string    `json:"tags"`
}

// UpdateTodoRequest defines model for UpdateTodoRequest.
type UpdateTodoRequest struct {
	Bucket      *UpdateTodoRequestBucket `json:"bucket,omitempty"`
	Description *string                  `json:"description,omitempty"`
	Done        *bool                    `json:"done,omitempty"`
	Title       *string                  `json:"title,omitempty"`
}

// MemoState defines enum values
type MemoState string

// TodoItemBucket defines enum values
type TodoItemBucket string

// UpdateTodoRequestBucket defines enum values
type UpdateTodoRequestBucket string

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	Q      *string `query:"q" json:"q,omitempty"`
	Limit  *int32  `query:"limit" json:"limit,omitempty"`
	Offset *int32  `query:"offset" json:"offset,omitempty"`
}

// ListMemosParams defines parameters for ListMemos.
type ListMemosParams struct {
	Q      *string    `query:"q" json:"q,omitempty"`
	Tag    *string    `query:"tag" json:"tag,omitempty"`
	State  *MemoState `query:"state" json:"state,omitempty"`
	Limit  *int32     `query:"limit" json:"limit,omitempty"`
	Offset *int32     `query:"offset" json:"offset,omitempty"`
}

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// CreateMemoJSONRequestBody defines body for CreateMemo for application/json ContentType.
type CreateMemoJSONRequestBody = CreateMemoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest

// UpdateMemoJSONRequestBody defines body for UpdateMemo for application/json ContentType.
type UpdateMemoJSONRequestBody = UpdateMemoRequest

// LinkAttachmentJSONRequestBody defines body for LinkAttachment for application/json ContentType.
type LinkAttachmentJSONRequestBody = LinkAttachmentRequest

// UnlinkAttachmentJSONRequestBody defines body for UnlinkAttachment for application/json ContentType.
type UnlinkAttachmentJSONRequestBody = LinkAttachmentRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{Server: server}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListTodos request
	ListTodos(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateTodoWithBody request with any body
	CreateTodoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateTodo(ctx context.Context, body CreateTodoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListTags request
	ListTags(ctx context.Context, params *ListTagsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListMemos request
	ListMemos(ctx context.Context, params *ListMemosParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateMemoWithBody request with any body
	CreateMemoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateMemo(ctx context.Context, body CreateMemoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCounter request
	GetCounter(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// IncrementCounter request
	IncrementCounter(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UploadAttachment request
	UploadAttachment(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateTodoWithBody request with any body
	UpdateTodoWithBody(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateTodo(ctx context.Context, id uuid.UUID, body UpdateTodoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteTodo request
	DeleteTodo(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListMemoBacklinks request
	ListMemoBacklinks(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMemo request
	GetMemo(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateMemoWithBody request with any body
	UpdateMemoWithBody(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateMemo(ctx context.Context, id uuid.UUID, body UpdateMemoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteMemo request
	DeleteMemo(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LinkAttachmentWithBody request with any body
	LinkAttachmentWithBody(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LinkAttachment(ctx context.Context, id uuid.UUID, body LinkAttachmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UnlinkAttachmentWithBody request with any body
	UnlinkAttachmentWithBody(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UnlinkAttachment(ctx context.Context, id uuid.UUID, body UnlinkAttachmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadAttachment request
	DownloadAttachment(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAttachment request
	GetAttachment(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAttachment request
	DeleteAttachment(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListAttachmentsByResource request
	ListAttachmentsByResource(ctx context.Context, resourceType string, resourceId uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListTodos(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTodosRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTodoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTodoRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTodo(ctx context.Context, body CreateTodoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.CreateTodoWithBody(ctx, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) ListTags(ctx context.Context, params *ListTagsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTagsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListMemos(ctx context.Context, params *ListMemosParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListMemosRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateMemoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateMemoRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateMemo(ctx context.Context, body CreateMemoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.CreateMemoWithBody(ctx, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) GetCounter(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCounterRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) IncrementCounter(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIncrementCounterRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UploadAttachment(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadAttachmentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateTodoWithBody(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateTodoRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateTodo(ctx context.Context, id uuid.UUID, body UpdateTodoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.UpdateTodoWithBody(ctx, id, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) DeleteTodo(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteTodoRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListMemoBacklinks(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListMemoBacklinksRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMemo(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMemoRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateMemoWithBody(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateMemoRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateMemo(ctx context.Context, id uuid.UUID, body UpdateMemoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.UpdateMemoWithBody(ctx, id, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) DeleteMemo(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteMemoRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LinkAttachmentWithBody(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLinkAttachmentRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LinkAttachment(ctx context.Context, id uuid.UUID, body LinkAttachmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.LinkAttachmentWithBody(ctx, id, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) UnlinkAttachmentWithBody(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnlinkAttachmentRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UnlinkAttachment(ctx context.Context, id uuid.UUID, body UnlinkAttachmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return c.UnlinkAttachmentWithBody(ctx, id, "application/json", bytes.NewReader(bodyBytes), reqEditors...)
}

func (c *Client) DownloadAttachment(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadAttachmentRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAttachment(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAttachmentRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAttachment(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAttachmentRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListAttachmentsByResource(ctx context.Context, resourceType string, resourceId uuid.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAttachmentsByResourceRequest(c.Server, resourceType, resourceId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListTodosRequest generates requests for ListTodos
func NewListTodosRequest(server string) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/todos")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewCreateTodoRequestWithBody generates requests for CreateTodo with any body
func NewCreateTodoRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/todos")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewCreateTodoRequest generates requests for CreateTodo
func NewCreateTodoRequest(server string, body CreateTodoJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewCreateTodoRequestWithBody(server, "application/json", bytes.NewReader(bodyBytes))
}

// NewListTagsRequest generates requests for ListTags
func NewListTagsRequest(server string, params *ListTagsParams) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tags")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()
		if params.Q != nil {
			queryValues.Set("q", fmt.Sprintf("%v", *params.Q))
		}
		if params.Limit != nil {
			queryValues.Set("limit", fmt.Sprintf("%v", *params.Limit))
		}
		if params.Offset != nil {
			queryValues.Set("offset", fmt.Sprintf("%v", *params.Offset))
		}
		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewListMemosRequest generates requests for ListMemos
func NewListMemosRequest(server string, params *ListMemosParams) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memos")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()
		if params.Q != nil {
			queryValues.Set("q", fmt.Sprintf("%v", *params.Q))
		}
		if params.Tag != nil {
			queryValues.Set("tag", fmt.Sprintf("%v", *params.Tag))
		}
		if params.State != nil {
			queryValues.Set("state", fmt.Sprintf("%v", *params.State))
		}
		if params.Limit != nil {
			queryValues.Set("limit", fmt.Sprintf("%v", *params.Limit))
		}
		if params.Offset != nil {
			queryValues.Set("offset", fmt.Sprintf("%v", *params.Offset))
		}
		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewCreateMemoRequestWithBody generates requests for CreateMemo with any body
func NewCreateMemoRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memos")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewCreateMemoRequest generates requests for CreateMemo
func NewCreateMemoRequest(server string, body CreateMemoJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewCreateMemoRequestWithBody(server, "application/json", bytes.NewReader(bodyBytes))
}

// NewGetCounterRequest generates requests for GetCounter
func NewGetCounterRequest(server string) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/counter")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewIncrementCounterRequest generates requests for IncrementCounter
func NewIncrementCounterRequest(server string) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/counter")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewUploadAttachmentRequest generates requests for UploadAttachment
func NewUploadAttachmentRequest(server string) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/attachments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewUpdateTodoRequestWithBody generates requests for UpdateTodo with any body
func NewUpdateTodoRequestWithBody(server string, id uuid.UUID, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/todos/%v", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewUpdateTodoRequest generates requests for UpdateTodo
func NewUpdateTodoRequest(server string, id uuid.UUID, body UpdateTodoJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewUpdateTodoRequestWithBody(server, id, "application/json", bytes.NewReader(bodyBytes))
}

// NewDeleteTodoRequest generates requests for DeleteTodo
func NewDeleteTodoRequest(server string, id uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/todos/%v", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewListMemoBacklinksRequest generates requests for ListMemoBacklinks
func NewListMemoBacklinksRequest(server string, id uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memos/%v/backlinks", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewGetMemoRequest generates requests for GetMemo
func NewGetMemoRequest(server string, id uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memos/%v", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewUpdateMemoRequestWithBody generates requests for UpdateMemo with any body
func NewUpdateMemoRequestWithBody(server string, id uuid.UUID, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memos/%v", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewUpdateMemoRequest generates requests for UpdateMemo
func NewUpdateMemoRequest(server string, id uuid.UUID, body UpdateMemoJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewUpdateMemoRequestWithBody(server, id, "application/json", bytes.NewReader(bodyBytes))
}

// NewDeleteMemoRequest generates requests for DeleteMemo
func NewDeleteMemoRequest(server string, id uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/memos/%v", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewLinkAttachmentRequestWithBody generates requests for LinkAttachment with any body
func NewLinkAttachmentRequestWithBody(server string, id uuid.UUID, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/attachments/%v/links", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewLinkAttachmentRequest generates requests for LinkAttachment
func NewLinkAttachmentRequest(server string, id uuid.UUID, body LinkAttachmentJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewLinkAttachmentRequestWithBody(server, id, "application/json", bytes.NewReader(bodyBytes))
}

// NewUnlinkAttachmentRequestWithBody generates requests for UnlinkAttachment with any body
func NewUnlinkAttachmentRequestWithBody(server string, id uuid.UUID, contentType string, body io.Reader) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/attachments/%v/links", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	return req, nil
}

// NewUnlinkAttachmentRequest generates requests for UnlinkAttachment
func NewUnlinkAttachmentRequest(server string, id uuid.UUID, body UnlinkAttachmentJSONRequestBody) (*http.Request, error) {
	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	return NewUnlinkAttachmentRequestWithBody(server, id, "application/json", bytes.NewReader(bodyBytes))
}

// NewDownloadAttachmentRequest generates requests for DownloadAttachment
func NewDownloadAttachmentRequest(server string, id uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/attachments/%v/content", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewGetAttachmentRequest generates requests for GetAttachment
func NewGetAttachmentRequest(server string, id uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/attachments/%v", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewDeleteAttachmentRequest generates requests for DeleteAttachment
func NewDeleteAttachmentRequest(server string, id uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/attachments/%v", id)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// NewListAttachmentsByResourceRequest generates requests for ListAttachmentsByResource
func NewListAttachmentsByResourceRequest(server string, resourceType string, resourceId uuid.UUID) (*http.Request, error) {
	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/resources/%v/%v/attachments", resourceType, resourceId)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListTodosWithResponse request
	ListTodosWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListTodosResponse, error)

	// CreateTodoWithBodyWithResponse request with any body
	CreateTodoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTodoResponse, error)

	CreateTodoWithResponse(ctx context.Context, body CreateTodoJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTodoResponse, error)

	// ListTagsWithResponse request
	ListTagsWithResponse(ctx context.Context, params *ListTagsParams, reqEditors ...RequestEditorFn) (*ListTagsResponse, error)

	// ListMemosWithResponse request
	ListMemosWithResponse(ctx context.Context, params *ListMemosParams, reqEditors ...RequestEditorFn) (*ListMemosResponse, error)

	// CreateMemoWithBodyWithResponse request with any body
	CreateMemoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateMemoResponse, error)

	CreateMemoWithResponse(ctx context.Context, body CreateMemoJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateMemoResponse, error)

	// GetCounterWithResponse request
	GetCounterWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCounterResponse, error)

	// IncrementCounterWithResponse request
	IncrementCounterWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*IncrementCounterResponse, error)

	// UploadAttachmentWithResponse request
	UploadAttachmentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*UploadAttachmentResponse, error)

	// UpdateTodoWithBodyWithResponse request with any body
	UpdateTodoWithBodyWithResponse(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateTodoResponse, error)

	UpdateTodoWithResponse(ctx context.Context, id uuid.UUID, body UpdateTodoJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateTodoResponse, error)

	// DeleteTodoWithResponse request
	DeleteTodoWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteTodoResponse, error)

	// ListMemoBacklinksWithResponse request
	ListMemoBacklinksWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*ListMemoBacklinksResponse, error)

	// GetMemoWithResponse request
	GetMemoWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*GetMemoResponse, error)

	// UpdateMemoWithBodyWithResponse request with any body
	UpdateMemoWithBodyWithResponse(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateMemoResponse, error)

	UpdateMemoWithResponse(ctx context.Context, id uuid.UUID, body UpdateMemoJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateMemoResponse, error)

	// DeleteMemoWithResponse request
	DeleteMemoWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteMemoResponse, error)

	// LinkAttachmentWithBodyWithResponse request with any body
	LinkAttachmentWithBodyWithResponse(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LinkAttachmentResponse, error)

	LinkAttachmentWithResponse(ctx context.Context, id uuid.UUID, body LinkAttachmentJSONRequestBody, reqEditors ...RequestEditorFn) (*LinkAttachmentResponse, error)

	// UnlinkAttachmentWithBodyWithResponse request with any body
	UnlinkAttachmentWithBodyWithResponse(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UnlinkAttachmentResponse, error)

	UnlinkAttachmentWithResponse(ctx context.Context, id uuid.UUID, body UnlinkAttachmentJSONRequestBody, reqEditors ...RequestEditorFn) (*UnlinkAttachmentResponse, error)

	// DownloadAttachmentWithResponse request
	DownloadAttachmentWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DownloadAttachmentResponse, error)

	// GetAttachmentWithResponse request
	GetAttachmentWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*GetAttachmentResponse, error)

	// DeleteAttachmentWithResponse request
	DeleteAttachmentWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteAttachmentResponse, error)

	// ListAttachmentsByResourceWithResponse request
	ListAttachmentsByResourceWithResponse(ctx context.Context, resourceType string, resourceId uuid.UUID, reqEditors ...RequestEditorFn) (*ListAttachmentsByResourceResponse, error)
}

type ListTodosResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TodoItem
}

// Status returns HTTPResponse.Status
func (r ListTodosResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTodosResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateTodoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *TodoItem
}

// Status returns HTTPResponse.Status
func (r CreateTodoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateTodoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListTagsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TagSummary
}

// Status returns HTTPResponse.Status
func (r ListTagsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTagsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListMemosResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]MemoSummary
}

// Status returns HTTPResponse.Status
func (r ListMemosResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListMemosResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateMemoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Memo
}

// Status returns HTTPResponse.Status
func (r CreateMemoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateMemoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCounterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Counter
}

// Status returns HTTPResponse.Status
func (r GetCounterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCounterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type IncrementCounterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r IncrementCounterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r IncrementCounterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UploadAttachmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Attachment
}

// Status returns HTTPResponse.Status
func (r UploadAttachmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadAttachmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateTodoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TodoItem
}

// Status returns HTTPResponse.Status
func (r UpdateTodoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateTodoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteTodoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteTodoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteTodoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListMemoBacklinksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]MemoSummary
}

// Status returns HTTPResponse.Status
func (r ListMemoBacklinksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListMemoBacklinksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMemoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Memo
}

// Status returns HTTPResponse.Status
func (r GetMemoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMemoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateMemoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Memo
}

// Status returns HTTPResponse.Status
func (r UpdateMemoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateMemoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteMemoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteMemoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteMemoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LinkAttachmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r LinkAttachmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LinkAttachmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UnlinkAttachmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UnlinkAttachmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UnlinkAttachmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadAttachmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DownloadAttachmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadAttachmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAttachmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Attachment
}

// Status returns HTTPResponse.Status
func (r GetAttachmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAttachmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAttachmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteAttachmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAttachmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListAttachmentsByResourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Attachment
}

// Status returns HTTPResponse.Status
func (r ListAttachmentsByResourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAttachmentsByResourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListTodosWithResponse request returning *ListTodosResponse
func (c *ClientWithResponses) ListTodosWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListTodosResponse, error) {
	rsp, err := c.ListTodos(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTodosResponse(rsp)
}

// CreateTodoWithBodyWithResponse request with arbitrary body returning *CreateTodoResponse
func (c *ClientWithResponses) CreateTodoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTodoResponse, error) {
	rsp, err := c.CreateTodoWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTodoResponse(rsp)
}

func (c *ClientWithResponses) CreateTodoWithResponse(ctx context.Context, body CreateTodoJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTodoResponse, error) {
	rsp, err := c.CreateTodo(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTodoResponse(rsp)
}

// ListTagsWithResponse request returning *ListTagsResponse
func (c *ClientWithResponses) ListTagsWithResponse(ctx context.Context, params *ListTagsParams, reqEditors ...RequestEditorFn) (*ListTagsResponse, error) {
	rsp, err := c.ListTags(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTagsResponse(rsp)
}

// ListMemosWithResponse request returning *ListMemosResponse
func (c *ClientWithResponses) ListMemosWithResponse(ctx context.Context, params *ListMemosParams, reqEditors ...RequestEditorFn) (*ListMemosResponse, error) {
	rsp, err := c.ListMemos(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListMemosResponse(rsp)
}

// CreateMemoWithBodyWithResponse request with arbitrary body returning *CreateMemoResponse
func (c *ClientWithResponses) CreateMemoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateMemoResponse, error) {
	rsp, err := c.CreateMemoWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateMemoResponse(rsp)
}

func (c *ClientWithResponses) CreateMemoWithResponse(ctx context.Context, body CreateMemoJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateMemoResponse, error) {
	rsp, err := c.CreateMemo(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateMemoResponse(rsp)
}

// GetCounterWithResponse request returning *GetCounterResponse
func (c *ClientWithResponses) GetCounterWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCounterResponse, error) {
	rsp, err := c.GetCounter(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCounterResponse(rsp)
}

// IncrementCounterWithResponse request returning *IncrementCounterResponse
func (c *ClientWithResponses) IncrementCounterWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*IncrementCounterResponse, error) {
	rsp, err := c.IncrementCounter(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIncrementCounterResponse(rsp)
}

// UploadAttachmentWithResponse request returning *UploadAttachmentResponse
func (c *ClientWithResponses) UploadAttachmentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*UploadAttachmentResponse, error) {
	rsp, err := c.UploadAttachment(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadAttachmentResponse(rsp)
}

// UpdateTodoWithBodyWithResponse request with arbitrary body returning *UpdateTodoResponse
func (c *ClientWithResponses) UpdateTodoWithBodyWithResponse(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateTodoResponse, error) {
	rsp, err := c.UpdateTodoWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateTodoResponse(rsp)
}

func (c *ClientWithResponses) UpdateTodoWithResponse(ctx context.Context, id uuid.UUID, body UpdateTodoJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateTodoResponse, error) {
	rsp, err := c.UpdateTodo(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateTodoResponse(rsp)
}

// DeleteTodoWithResponse request returning *DeleteTodoResponse
func (c *ClientWithResponses) DeleteTodoWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteTodoResponse, error) {
	rsp, err := c.DeleteTodo(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteTodoResponse(rsp)
}

// ListMemoBacklinksWithResponse request returning *ListMemoBacklinksResponse
func (c *ClientWithResponses) ListMemoBacklinksWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*ListMemoBacklinksResponse, error) {
	rsp, err := c.ListMemoBacklinks(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListMemoBacklinksResponse(rsp)
}

// GetMemoWithResponse request returning *GetMemoResponse
func (c *ClientWithResponses) GetMemoWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*GetMemoResponse, error) {
	rsp, err := c.GetMemo(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMemoResponse(rsp)
}

// UpdateMemoWithBodyWithResponse request with arbitrary body returning *UpdateMemoResponse
func (c *ClientWithResponses) UpdateMemoWithBodyWithResponse(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateMemoResponse, error) {
	rsp, err := c.UpdateMemoWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateMemoResponse(rsp)
}

func (c *ClientWithResponses) UpdateMemoWithResponse(ctx context.Context, id uuid.UUID, body UpdateMemoJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateMemoResponse, error) {
	rsp, err := c.UpdateMemo(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateMemoResponse(rsp)
}

// DeleteMemoWithResponse request returning *DeleteMemoResponse
func (c *ClientWithResponses) DeleteMemoWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteMemoResponse, error) {
	rsp, err := c.DeleteMemo(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteMemoResponse(rsp)
}

// LinkAttachmentWithBodyWithResponse request with arbitrary body returning *LinkAttachmentResponse
func (c *ClientWithResponses) LinkAttachmentWithBodyWithResponse(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LinkAttachmentResponse, error) {
	rsp, err := c.LinkAttachmentWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLinkAttachmentResponse(rsp)
}

func (c *ClientWithResponses) LinkAttachmentWithResponse(ctx context.Context, id uuid.UUID, body LinkAttachmentJSONRequestBody, reqEditors ...RequestEditorFn) (*LinkAttachmentResponse, error) {
	rsp, err := c.LinkAttachment(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLinkAttachmentResponse(rsp)
}

// UnlinkAttachmentWithBodyWithResponse request with arbitrary body returning *UnlinkAttachmentResponse
func (c *ClientWithResponses) UnlinkAttachmentWithBodyWithResponse(ctx context.Context, id uuid.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UnlinkAttachmentResponse, error) {
	rsp, err := c.UnlinkAttachmentWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnlinkAttachmentResponse(rsp)
}

func (c *ClientWithResponses) UnlinkAttachmentWithResponse(ctx context.Context, id uuid.UUID, body UnlinkAttachmentJSONRequestBody, reqEditors ...RequestEditorFn) (*UnlinkAttachmentResponse, error) {
	rsp, err := c.UnlinkAttachment(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnlinkAttachmentResponse(rsp)
}

// DownloadAttachmentWithResponse request returning *DownloadAttachmentResponse
func (c *ClientWithResponses) DownloadAttachmentWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DownloadAttachmentResponse, error) {
	rsp, err := c.DownloadAttachment(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadAttachmentResponse(rsp)
}

// GetAttachmentWithResponse request returning *GetAttachmentResponse
func (c *ClientWithResponses) GetAttachmentWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*GetAttachmentResponse, error) {
	rsp, err := c.GetAttachment(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAttachmentResponse(rsp)
}

// DeleteAttachmentWithResponse request returning *DeleteAttachmentResponse
func (c *ClientWithResponses) DeleteAttachmentWithResponse(ctx context.Context, id uuid.UUID, reqEditors ...RequestEditorFn) (*DeleteAttachmentResponse, error) {
	rsp, err := c.DeleteAttachment(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAttachmentResponse(rsp)
}

// ListAttachmentsByResourceWithResponse request returning *ListAttachmentsByResourceResponse
func (c *ClientWithResponses) ListAttachmentsByResourceWithResponse(ctx context.Context, resourceType string, resourceId uuid.UUID, reqEditors ...RequestEditorFn) (*ListAttachmentsByResourceResponse, error) {
	rsp, err := c.ListAttachmentsByResource(ctx, resourceType, resourceId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAttachmentsByResourceResponse(rsp)
}

// ParseListTodosResponse parses an HTTP response from a ListTodosWithResponse call
func ParseListTodosResponse(rsp *http.Response) (*ListTodosResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTodosResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TodoItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseCreateTodoResponse parses an HTTP response from a CreateTodoWithResponse call
func ParseCreateTodoResponse(rsp *http.Response) (*CreateTodoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateTodoResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest TodoItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest
	}

	return response, nil
}

// ParseListTagsResponse parses an HTTP response from a ListTagsWithResponse call
func ParseListTagsResponse(rsp *http.Response) (*ListTagsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTagsResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TagSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseListMemosResponse parses an HTTP response from a ListMemosWithResponse call
func ParseListMemosResponse(rsp *http.Response) (*ListMemosResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListMemosResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []MemoSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseCreateMemoResponse parses an HTTP response from a CreateMemoWithResponse call
func ParseCreateMemoResponse(rsp *http.Response) (*CreateMemoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateMemoResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Memo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest
	}

	return response, nil
}

// ParseGetCounterResponse parses an HTTP response from a GetCounterWithResponse call
func ParseGetCounterResponse(rsp *http.Response) (*GetCounterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCounterResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Counter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseIncrementCounterResponse parses an HTTP response from a IncrementCounterWithResponse call
func ParseIncrementCounterResponse(rsp *http.Response) (*IncrementCounterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &IncrementCounterResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseUploadAttachmentResponse parses an HTTP response from a UploadAttachmentWithResponse call
func ParseUploadAttachmentResponse(rsp *http.Response) (*UploadAttachmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadAttachmentResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Attachment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest
	}

	return response, nil
}

// ParseUpdateTodoResponse parses an HTTP response from a UpdateTodoWithResponse call
func ParseUpdateTodoResponse(rsp *http.Response) (*UpdateTodoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateTodoResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TodoItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseDeleteTodoResponse parses an HTTP response from a DeleteTodoWithResponse call
func ParseDeleteTodoResponse(rsp *http.Response) (*DeleteTodoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteTodoResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseListMemoBacklinksResponse parses an HTTP response from a ListMemoBacklinksWithResponse call
func ParseListMemoBacklinksResponse(rsp *http.Response) (*ListMemoBacklinksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListMemoBacklinksResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []MemoSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseGetMemoResponse parses an HTTP response from a GetMemoWithResponse call
func ParseGetMemoResponse(rsp *http.Response) (*GetMemoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMemoResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Memo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseUpdateMemoResponse parses an HTTP response from a UpdateMemoWithResponse call
func ParseUpdateMemoResponse(rsp *http.Response) (*UpdateMemoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateMemoResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Memo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseDeleteMemoResponse parses an HTTP response from a DeleteMemoWithResponse call
func ParseDeleteMemoResponse(rsp *http.Response) (*DeleteMemoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteMemoResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseLinkAttachmentResponse parses an HTTP response from a LinkAttachmentWithResponse call
func ParseLinkAttachmentResponse(rsp *http.Response) (*LinkAttachmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LinkAttachmentResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseUnlinkAttachmentResponse parses an HTTP response from a UnlinkAttachmentWithResponse call
func ParseUnlinkAttachmentResponse(rsp *http.Response) (*UnlinkAttachmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UnlinkAttachmentResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseDownloadAttachmentResponse parses an HTTP response from a DownloadAttachmentWithResponse call
func ParseDownloadAttachmentResponse(rsp *http.Response) (*DownloadAttachmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadAttachmentResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseGetAttachmentResponse parses an HTTP response from a GetAttachmentWithResponse call
func ParseGetAttachmentResponse(rsp *http.Response) (*GetAttachmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAttachmentResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Attachment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ParseDeleteAttachmentResponse parses an HTTP response from a DeleteAttachmentWithResponse call
func ParseDeleteAttachmentResponse(rsp *http.Response) (*DeleteAttachmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAttachmentResponse{Body: bodyBytes, HTTPResponse: rsp}

	return response, nil
}

// ParseListAttachmentsByResourceResponse parses an HTTP response from a ListAttachmentsByResourceWithResponse call
func ParseListAttachmentsByResourceResponse(rsp *http.Response) (*ListAttachmentsByResourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAttachmentsByResourceResponse{Body: bodyBytes, HTTPResponse: rsp}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Attachment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List TODO items for current user
	// (GET /todos)
	ListTodos(c fiber.Ctx) error
	// Create a new TODO item
	// (POST /todos)
	CreateTodo(c fiber.Ctx) error
	// List tags for current user
	// (GET /tags)
	ListTags(c fiber.Ctx, params ListTagsParams) error
	// List memos for current user
	// (GET /memos)
	ListMemos(c fiber.Ctx, params ListMemosParams) error
	// Create a new memo
	// (POST /memos)
	CreateMemo(c fiber.Ctx) error
	// Get Counter
	// (GET /counter)
	GetCounter(c fiber.Ctx) error
	// Increment Counter
	// (POST /counter)
	IncrementCounter(c fiber.Ctx) error
	// Upload attachment
	// (POST /attachments)
	UploadAttachment(c fiber.Ctx) error
	// Update a TODO item
	// (PATCH /todos/{id})
	UpdateTodo(c fiber.Ctx, id uuid.UUID) error
	// Delete a TODO item
	// (DELETE /todos/{id})
	DeleteTodo(c fiber.Ctx, id uuid.UUID) error
	// List backlinks for a memo
	// (GET /memos/{id}/backlinks)
	ListMemoBacklinks(c fiber.Ctx, id uuid.UUID) error
	// Get memo by ID
	// (GET /memos/{id})
	GetMemo(c fiber.Ctx, id uuid.UUID) error
	// Update a memo
	// (PATCH /memos/{id})
	UpdateMemo(c fiber.Ctx, id uuid.UUID) error
	// Delete a memo
	// (DELETE /memos/{id})
	DeleteMemo(c fiber.Ctx, id uuid.UUID) error
	// Link attachment to a resource
	// (POST /attachments/{id}/links)
	LinkAttachment(c fiber.Ctx, id uuid.UUID) error
	// Unlink attachment from a resource
	// (DELETE /attachments/{id}/links)
	UnlinkAttachment(c fiber.Ctx, id uuid.UUID) error
	// Download attachment content
	// (GET /attachments/{id}/content)
	DownloadAttachment(c fiber.Ctx, id uuid.UUID) error
	// Get attachment metadata
	// (GET /attachments/{id})
	GetAttachment(c fiber.Ctx, id uuid.UUID) error
	// Delete attachment
	// (DELETE /attachments/{id})
	DeleteAttachment(c fiber.Ctx, id uuid.UUID) error
	// List attachments by resource
	// (GET /resources/{resourceType}/{resourceId}/attachments)
	ListAttachmentsByResource(c fiber.Ctx, resourceType string, resourceId uuid.UUID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(c fiber.Ctx) error {
	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.ListTodos(c)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(c fiber.Ctx) error {
	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.CreateTodo(c)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(c fiber.Ctx) error {
	var params ListTagsParams
	if err := c.Bind().Query(&params); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.ListTags(c, params)
}

// ListMemos operation middleware
func (siw *ServerInterfaceWrapper) ListMemos(c fiber.Ctx) error {
	var params ListMemosParams
	if err := c.Bind().Query(&params); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.ListMemos(c, params)
}

// CreateMemo operation middleware
func (siw *ServerInterfaceWrapper) CreateMemo(c fiber.Ctx) error {
	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.CreateMemo(c)
}

// GetCounter operation middleware
func (siw *ServerInterfaceWrapper) GetCounter(c fiber.Ctx) error {
	return siw.Handler.GetCounter(c)
}

// IncrementCounter operation middleware
func (siw *ServerInterfaceWrapper) IncrementCounter(c fiber.Ctx) error {
	fiber.StoreInContext(c, BearerAuthScopes, []string{"x.OperationPermit(c, operationID)"})

	return siw.Handler.IncrementCounter(c)
}

// UploadAttachment operation middleware
func (siw *ServerInterfaceWrapper) UploadAttachment(c fiber.Ctx) error {
	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.UploadAttachment(c)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.UpdateTodo(c, id)
}

// DeleteTodo operation middleware
func (siw *ServerInterfaceWrapper) DeleteTodo(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.DeleteTodo(c, id)
}

// ListMemoBacklinks operation middleware
func (siw *ServerInterfaceWrapper) ListMemoBacklinks(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.ListMemoBacklinks(c, id)
}

// GetMemo operation middleware
func (siw *ServerInterfaceWrapper) GetMemo(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.GetMemo(c, id)
}

// UpdateMemo operation middleware
func (siw *ServerInterfaceWrapper) UpdateMemo(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.UpdateMemo(c, id)
}

// DeleteMemo operation middleware
func (siw *ServerInterfaceWrapper) DeleteMemo(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.DeleteMemo(c, id)
}

// LinkAttachment operation middleware
func (siw *ServerInterfaceWrapper) LinkAttachment(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.LinkAttachment(c, id)
}

// UnlinkAttachment operation middleware
func (siw *ServerInterfaceWrapper) UnlinkAttachment(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.UnlinkAttachment(c, id)
}

// DownloadAttachment operation middleware
func (siw *ServerInterfaceWrapper) DownloadAttachment(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.DownloadAttachment(c, id)
}

// GetAttachment operation middleware
func (siw *ServerInterfaceWrapper) GetAttachment(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.GetAttachment(c, id)
}

// DeleteAttachment operation middleware
func (siw *ServerInterfaceWrapper) DeleteAttachment(c fiber.Ctx) error {
	var id uuid.UUID
	idValue := c.Params("id")
	parsedId, err := uuid.Parse(idValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}
	id = parsedId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.DeleteAttachment(c, id)
}

// ListAttachmentsByResource operation middleware
func (siw *ServerInterfaceWrapper) ListAttachmentsByResource(c fiber.Ctx) error {
	var resourceType string
	resourceType = c.Params("resourceType")

	var resourceId uuid.UUID
	resourceIdValue := c.Params("resourceId")
	parsedResourceId, err := uuid.Parse(resourceIdValue)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter resourceId: %w", err).Error())
	}
	resourceId = parsedResourceId

	fiber.StoreInContext(c, BearerAuthScopes, []string{})

	return siw.Handler.ListAttachmentsByResource(c, resourceType, resourceId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{Handler: si}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/todos", wrapper.ListTodos)

	router.Post(options.BaseURL+"/todos", wrapper.CreateTodo)

	router.Get(options.BaseURL+"/tags", wrapper.ListTags)

	router.Get(options.BaseURL+"/memos", wrapper.ListMemos)

	router.Post(options.BaseURL+"/memos", wrapper.CreateMemo)

	router.Get(options.BaseURL+"/counter", wrapper.GetCounter)

	router.Post(options.BaseURL+"/counter", wrapper.IncrementCounter)

	router.Post(options.BaseURL+"/attachments", wrapper.UploadAttachment)

	router.Patch(options.BaseURL+"/todos/:id", wrapper.UpdateTodo)

	router.Delete(options.BaseURL+"/todos/:id", wrapper.DeleteTodo)

	router.Get(options.BaseURL+"/memos/:id/backlinks", wrapper.ListMemoBacklinks)

	router.Get(options.BaseURL+"/memos/:id", wrapper.GetMemo)

	router.Patch(options.BaseURL+"/memos/:id", wrapper.UpdateMemo)

	router.Delete(options.BaseURL+"/memos/:id", wrapper.DeleteMemo)

	router.Post(options.BaseURL+"/attachments/:id/links", wrapper.LinkAttachment)

	router.Delete(options.BaseURL+"/attachments/:id/links", wrapper.UnlinkAttachment)

	router.Get(options.BaseURL+"/attachments/:id/content", wrapper.DownloadAttachment)

	router.Get(options.BaseURL+"/attachments/:id", wrapper.GetAttachment)

	router.Delete(options.BaseURL+"/attachments/:id", wrapper.DeleteAttachment)

	router.Get(options.BaseURL+"/resources/:resourceType/:resourceId/attachments", wrapper.ListAttachmentsByResource)

}

type Validator interface {
	// AuthFunc is called before the request is processed. The response will be 401 if the auth fails.
	AuthFunc(fiber.Ctx) error

	// PreValidate is called before the request is processed. The response will be 403 if the validation fails.
	PreValidate(fiber.Ctx) error

	// PostValidate is called after the request is processed. The response will be 403 if the validation fails.
	PostValidate(fiber.Ctx) error

	OperationPermit(c fiber.Ctx, operationID string) error
}

type XMiddleware struct {
	ServerInterface
	Validator
}

func NewXMiddleware(handler ServerInterface, validator Validator) ServerInterface {
	return &XMiddleware{ServerInterface: handler, Validator: validator}
}

// List TODO items for current user
// (GET /todos)
func (x *XMiddleware) ListTodos(c fiber.Ctx) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.ListTodos(c)
}

// Create a new TODO item
// (POST /todos)
func (x *XMiddleware) CreateTodo(c fiber.Ctx) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.CreateTodo(c)
}

// List tags for current user
// (GET /tags)
func (x *XMiddleware) ListTags(c fiber.Ctx, params ListTagsParams) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.ListTags(c, params)
}

// List memos for current user
// (GET /memos)
func (x *XMiddleware) ListMemos(c fiber.Ctx, params ListMemosParams) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.ListMemos(c, params)
}

// Create a new memo
// (POST /memos)
func (x *XMiddleware) CreateMemo(c fiber.Ctx) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.CreateMemo(c)
}

// Increment Counter
// (POST /counter)
func (x *XMiddleware) IncrementCounter(c fiber.Ctx) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	operationID := "IncrementCounter"
	if err := x.OperationPermit(c, operationID); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.IncrementCounter(c)
}

// Upload attachment
// (POST /attachments)
func (x *XMiddleware) UploadAttachment(c fiber.Ctx) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.UploadAttachment(c)
}

// Update a TODO item
// (PATCH /todos/{id})
func (x *XMiddleware) UpdateTodo(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.UpdateTodo(c, id)
}

// Delete a TODO item
// (DELETE /todos/{id})
func (x *XMiddleware) DeleteTodo(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.DeleteTodo(c, id)
}

// List backlinks for a memo
// (GET /memos/{id}/backlinks)
func (x *XMiddleware) ListMemoBacklinks(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.ListMemoBacklinks(c, id)
}

// Get memo by ID
// (GET /memos/{id})
func (x *XMiddleware) GetMemo(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.GetMemo(c, id)
}

// Update a memo
// (PATCH /memos/{id})
func (x *XMiddleware) UpdateMemo(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.UpdateMemo(c, id)
}

// Delete a memo
// (DELETE /memos/{id})
func (x *XMiddleware) DeleteMemo(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.DeleteMemo(c, id)
}

// Link attachment to a resource
// (POST /attachments/{id}/links)
func (x *XMiddleware) LinkAttachment(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.LinkAttachment(c, id)
}

// Unlink attachment from a resource
// (DELETE /attachments/{id}/links)
func (x *XMiddleware) UnlinkAttachment(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.UnlinkAttachment(c, id)
}

// Download attachment content
// (GET /attachments/{id}/content)
func (x *XMiddleware) DownloadAttachment(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.DownloadAttachment(c, id)
}

// Get attachment metadata
// (GET /attachments/{id})
func (x *XMiddleware) GetAttachment(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.GetAttachment(c, id)
}

// Delete attachment
// (DELETE /attachments/{id})
func (x *XMiddleware) DeleteAttachment(c fiber.Ctx, id uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.DeleteAttachment(c, id)
}

// List attachments by resource
// (GET /resources/{resourceType}/{resourceId}/attachments)
func (x *XMiddleware) ListAttachmentsByResource(c fiber.Ctx, resourceType string, resourceId uuid.UUID) error {
	if err := x.AuthFunc(c); err != nil {
		return c.Status(fiber.StatusUnauthorized).SendString(err.Error())
	}
	if err := x.PreValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	if err := x.PostValidate(c); err != nil {
		return c.Status(fiber.StatusForbidden).SendString(err.Error())
	}
	return x.ServerInterface.ListAttachmentsByResource(c, resourceType, resourceId)
}
