// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/zcore/model/model.go
//
// Generated by this command:
//
//	mockgen -source pkg/zcore/model/model.go -destination pkg/zcore/model/mock_gen.go -package model
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	querier "github.com/wibus-wee/allinone/pkg/zgen/querier"
	gomock "go.uber.org/mock/gomock"
)

// MockModelInterface is a mock of ModelInterface interface.
type MockModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockModelInterfaceMockRecorder
	isgomock struct{}
}

// MockModelInterfaceMockRecorder is the mock recorder for MockModelInterface.
type MockModelInterfaceMockRecorder struct {
	mock *MockModelInterface
}

// NewMockModelInterface creates a new mock instance.
func NewMockModelInterface(ctrl *gomock.Controller) *MockModelInterface {
	mock := &MockModelInterface{ctrl: ctrl}
	mock.recorder = &MockModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelInterface) EXPECT() *MockModelInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockModelInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockModelInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockModelInterface)(nil).Close))
}

// CreateTodo mocks base method.
func (m *MockModelInterface) CreateTodo(ctx context.Context, arg querier.CreateTodoParams) (*querier.TodoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", ctx, arg)
	ret0, _ := ret[0].(*querier.TodoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockModelInterfaceMockRecorder) CreateTodo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockModelInterface)(nil).CreateTodo), ctx, arg)
}

// DeleteTodo mocks base method.
func (m *MockModelInterface) DeleteTodo(ctx context.Context, arg querier.DeleteTodoParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockModelInterfaceMockRecorder) DeleteTodo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockModelInterface)(nil).DeleteTodo), ctx, arg)
}

// EnsureUser mocks base method.
func (m *MockModelInterface) EnsureUser(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureUser indicates an expected call of EnsureUser.
func (mr *MockModelInterfaceMockRecorder) EnsureUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureUser", reflect.TypeOf((*MockModelInterface)(nil).EnsureUser), ctx, id)
}

// GetCounter mocks base method.
func (m *MockModelInterface) GetCounter(ctx context.Context) (*querier.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx)
	ret0, _ := ret[0].(*querier.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockModelInterfaceMockRecorder) GetCounter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockModelInterface)(nil).GetCounter), ctx)
}

// InTransaction mocks base method.
func (m *MockModelInterface) InTransaction() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction")
	ret0, _ := ret[0].(bool)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockModelInterfaceMockRecorder) InTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*MockModelInterface)(nil).InTransaction))
}

// IncrementCounter mocks base method.
func (m *MockModelInterface) IncrementCounter(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockModelInterfaceMockRecorder) IncrementCounter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockModelInterface)(nil).IncrementCounter), ctx)
}

// ListTodosByUser mocks base method.
func (m *MockModelInterface) ListTodosByUser(ctx context.Context, userID int32) ([]*querier.TodoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodosByUser", ctx, userID)
	ret0, _ := ret[0].([]*querier.TodoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTodosByUser indicates an expected call of ListTodosByUser.
func (mr *MockModelInterfaceMockRecorder) ListTodosByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodosByUser", reflect.TypeOf((*MockModelInterface)(nil).ListTodosByUser), ctx, userID)
}

// NormalizeTodayToWeek mocks base method.
func (m *MockModelInterface) NormalizeTodayToWeek(ctx context.Context, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizeTodayToWeek", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NormalizeTodayToWeek indicates an expected call of NormalizeTodayToWeek.
func (mr *MockModelInterfaceMockRecorder) NormalizeTodayToWeek(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizeTodayToWeek", reflect.TypeOf((*MockModelInterface)(nil).NormalizeTodayToWeek), ctx, userID)
}

// NormalizeWeekToLater mocks base method.
func (m *MockModelInterface) NormalizeWeekToLater(ctx context.Context, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizeWeekToLater", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NormalizeWeekToLater indicates an expected call of NormalizeWeekToLater.
func (mr *MockModelInterfaceMockRecorder) NormalizeWeekToLater(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizeWeekToLater", reflect.TypeOf((*MockModelInterface)(nil).NormalizeWeekToLater), ctx, userID)
}

// RunTransaction mocks base method.
func (m *MockModelInterface) RunTransaction(ctx context.Context, f func(ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockModelInterfaceMockRecorder) RunTransaction(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockModelInterface)(nil).RunTransaction), ctx, f)
}

// RunTransactionWithTx mocks base method.
func (m *MockModelInterface) RunTransactionWithTx(ctx context.Context, f func(pgx.Tx, ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransactionWithTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransactionWithTx indicates an expected call of RunTransactionWithTx.
func (mr *MockModelInterfaceMockRecorder) RunTransactionWithTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransactionWithTx", reflect.TypeOf((*MockModelInterface)(nil).RunTransactionWithTx), ctx, f)
}

// SpawnWithTx mocks base method.
func (m *MockModelInterface) SpawnWithTx(tx pgx.Tx) ModelInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnWithTx", tx)
	ret0, _ := ret[0].(ModelInterface)
	return ret0
}

// SpawnWithTx indicates an expected call of SpawnWithTx.
func (mr *MockModelInterfaceMockRecorder) SpawnWithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnWithTx", reflect.TypeOf((*MockModelInterface)(nil).SpawnWithTx), tx)
}

// UpdateTodo mocks base method.
func (m *MockModelInterface) UpdateTodo(ctx context.Context, arg querier.UpdateTodoParams) (*querier.TodoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", ctx, arg)
	ret0, _ := ret[0].(*querier.TodoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockModelInterfaceMockRecorder) UpdateTodo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockModelInterface)(nil).UpdateTodo), ctx, arg)
}

// UpdateTodoBucket mocks base method.
func (m *MockModelInterface) UpdateTodoBucket(ctx context.Context, arg querier.UpdateTodoBucketParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodoBucket", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTodoBucket indicates an expected call of UpdateTodoBucket.
func (mr *MockModelInterfaceMockRecorder) UpdateTodoBucket(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodoBucket", reflect.TypeOf((*MockModelInterface)(nil).UpdateTodoBucket), ctx, arg)
}
