// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/zcore/model/model.go
//
// Generated by this command:
//
//	mockgen -source pkg/zcore/model/model.go -destination pkg/zcore/model/mock_gen.go -package model
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	querier "github.com/wibus-wee/allinone/pkg/zgen/querier"
	gomock "go.uber.org/mock/gomock"
)

// MockModelInterface is a mock of ModelInterface interface.
type MockModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockModelInterfaceMockRecorder
	isgomock struct{}
}

// MockModelInterfaceMockRecorder is the mock recorder for MockModelInterface.
type MockModelInterfaceMockRecorder struct {
	mock *MockModelInterface
}

// NewMockModelInterface creates a new mock instance.
func NewMockModelInterface(ctrl *gomock.Controller) *MockModelInterface {
	mock := &MockModelInterface{ctrl: ctrl}
	mock.recorder = &MockModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelInterface) EXPECT() *MockModelInterfaceMockRecorder {
	return m.recorder
}

// ApproveDeviceCode mocks base method.
func (m *MockModelInterface) ApproveDeviceCode(ctx context.Context, arg querier.ApproveDeviceCodeParams) (*querier.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveDeviceCode", ctx, arg)
	ret0, _ := ret[0].(*querier.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveDeviceCode indicates an expected call of ApproveDeviceCode.
func (mr *MockModelInterfaceMockRecorder) ApproveDeviceCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveDeviceCode", reflect.TypeOf((*MockModelInterface)(nil).ApproveDeviceCode), ctx, arg)
}

// Close mocks base method.
func (m *MockModelInterface) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockModelInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockModelInterface)(nil).Close))
}

// ConsumeDeviceCodeIfApproved mocks base method.
func (m *MockModelInterface) ConsumeDeviceCodeIfApproved(ctx context.Context, id int64) (*querier.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeDeviceCodeIfApproved", ctx, id)
	ret0, _ := ret[0].(*querier.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeDeviceCodeIfApproved indicates an expected call of ConsumeDeviceCodeIfApproved.
func (mr *MockModelInterfaceMockRecorder) ConsumeDeviceCodeIfApproved(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeDeviceCodeIfApproved", reflect.TypeOf((*MockModelInterface)(nil).ConsumeDeviceCodeIfApproved), ctx, id)
}

// CreateAttachment mocks base method.
func (m *MockModelInterface) CreateAttachment(ctx context.Context, arg querier.CreateAttachmentParams) (*querier.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttachment", ctx, arg)
	ret0, _ := ret[0].(*querier.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttachment indicates an expected call of CreateAttachment.
func (mr *MockModelInterfaceMockRecorder) CreateAttachment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttachment", reflect.TypeOf((*MockModelInterface)(nil).CreateAttachment), ctx, arg)
}

// CreateAttachmentLink mocks base method.
func (m *MockModelInterface) CreateAttachmentLink(ctx context.Context, arg querier.CreateAttachmentLinkParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttachmentLink", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttachmentLink indicates an expected call of CreateAttachmentLink.
func (mr *MockModelInterfaceMockRecorder) CreateAttachmentLink(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttachmentLink", reflect.TypeOf((*MockModelInterface)(nil).CreateAttachmentLink), ctx, arg)
}

// CreateDeviceCode mocks base method.
func (m *MockModelInterface) CreateDeviceCode(ctx context.Context, arg querier.CreateDeviceCodeParams) (*querier.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeviceCode", ctx, arg)
	ret0, _ := ret[0].(*querier.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeviceCode indicates an expected call of CreateDeviceCode.
func (mr *MockModelInterfaceMockRecorder) CreateDeviceCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeviceCode", reflect.TypeOf((*MockModelInterface)(nil).CreateDeviceCode), ctx, arg)
}

// CreateMemo mocks base method.
func (m *MockModelInterface) CreateMemo(ctx context.Context, arg querier.CreateMemoParams) (*querier.CreateMemoRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMemo", ctx, arg)
	ret0, _ := ret[0].(*querier.CreateMemoRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMemo indicates an expected call of CreateMemo.
func (mr *MockModelInterfaceMockRecorder) CreateMemo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMemo", reflect.TypeOf((*MockModelInterface)(nil).CreateMemo), ctx, arg)
}

// CreateMemoRelation mocks base method.
func (m *MockModelInterface) CreateMemoRelation(ctx context.Context, arg querier.CreateMemoRelationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMemoRelation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMemoRelation indicates an expected call of CreateMemoRelation.
func (mr *MockModelInterfaceMockRecorder) CreateMemoRelation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMemoRelation", reflect.TypeOf((*MockModelInterface)(nil).CreateMemoRelation), ctx, arg)
}

// CreateMemoTag mocks base method.
func (m *MockModelInterface) CreateMemoTag(ctx context.Context, arg querier.CreateMemoTagParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMemoTag", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMemoTag indicates an expected call of CreateMemoTag.
func (mr *MockModelInterfaceMockRecorder) CreateMemoTag(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMemoTag", reflect.TypeOf((*MockModelInterface)(nil).CreateMemoTag), ctx, arg)
}

// CreateTodo mocks base method.
func (m *MockModelInterface) CreateTodo(ctx context.Context, arg querier.CreateTodoParams) (*querier.CreateTodoRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", ctx, arg)
	ret0, _ := ret[0].(*querier.CreateTodoRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockModelInterfaceMockRecorder) CreateTodo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockModelInterface)(nil).CreateTodo), ctx, arg)
}

// DeleteAttachment mocks base method.
func (m *MockModelInterface) DeleteAttachment(ctx context.Context, arg querier.DeleteAttachmentParams) (*querier.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachment", ctx, arg)
	ret0, _ := ret[0].(*querier.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAttachment indicates an expected call of DeleteAttachment.
func (mr *MockModelInterfaceMockRecorder) DeleteAttachment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachment", reflect.TypeOf((*MockModelInterface)(nil).DeleteAttachment), ctx, arg)
}

// DeleteAttachmentLink mocks base method.
func (m *MockModelInterface) DeleteAttachmentLink(ctx context.Context, arg querier.DeleteAttachmentLinkParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachmentLink", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachmentLink indicates an expected call of DeleteAttachmentLink.
func (mr *MockModelInterfaceMockRecorder) DeleteAttachmentLink(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachmentLink", reflect.TypeOf((*MockModelInterface)(nil).DeleteAttachmentLink), ctx, arg)
}

// DeleteAttachmentLinksByResource mocks base method.
func (m *MockModelInterface) DeleteAttachmentLinksByResource(ctx context.Context, arg querier.DeleteAttachmentLinksByResourceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachmentLinksByResource", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachmentLinksByResource indicates an expected call of DeleteAttachmentLinksByResource.
func (mr *MockModelInterfaceMockRecorder) DeleteAttachmentLinksByResource(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachmentLinksByResource", reflect.TypeOf((*MockModelInterface)(nil).DeleteAttachmentLinksByResource), ctx, arg)
}

// DeleteMemo mocks base method.
func (m *MockModelInterface) DeleteMemo(ctx context.Context, arg querier.DeleteMemoParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMemo", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMemo indicates an expected call of DeleteMemo.
func (mr *MockModelInterfaceMockRecorder) DeleteMemo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMemo", reflect.TypeOf((*MockModelInterface)(nil).DeleteMemo), ctx, arg)
}

// DeleteMemoRelationsBySource mocks base method.
func (m *MockModelInterface) DeleteMemoRelationsBySource(ctx context.Context, arg querier.DeleteMemoRelationsBySourceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMemoRelationsBySource", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMemoRelationsBySource indicates an expected call of DeleteMemoRelationsBySource.
func (mr *MockModelInterfaceMockRecorder) DeleteMemoRelationsBySource(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMemoRelationsBySource", reflect.TypeOf((*MockModelInterface)(nil).DeleteMemoRelationsBySource), ctx, arg)
}

// DeleteMemoTagsByMemo mocks base method.
func (m *MockModelInterface) DeleteMemoTagsByMemo(ctx context.Context, arg querier.DeleteMemoTagsByMemoParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMemoTagsByMemo", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMemoTagsByMemo indicates an expected call of DeleteMemoTagsByMemo.
func (mr *MockModelInterfaceMockRecorder) DeleteMemoTagsByMemo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMemoTagsByMemo", reflect.TypeOf((*MockModelInterface)(nil).DeleteMemoTagsByMemo), ctx, arg)
}

// DeleteTodo mocks base method.
func (m *MockModelInterface) DeleteTodo(ctx context.Context, arg querier.DeleteTodoParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockModelInterfaceMockRecorder) DeleteTodo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockModelInterface)(nil).DeleteTodo), ctx, arg)
}

// EnsureUser mocks base method.
func (m *MockModelInterface) EnsureUser(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureUser indicates an expected call of EnsureUser.
func (mr *MockModelInterfaceMockRecorder) EnsureUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureUser", reflect.TypeOf((*MockModelInterface)(nil).EnsureUser), ctx, id)
}

// ExpireDeviceCodes mocks base method.
func (m *MockModelInterface) ExpireDeviceCodes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireDeviceCodes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireDeviceCodes indicates an expected call of ExpireDeviceCodes.
func (mr *MockModelInterfaceMockRecorder) ExpireDeviceCodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireDeviceCodes", reflect.TypeOf((*MockModelInterface)(nil).ExpireDeviceCodes), ctx)
}

// GetAttachmentByID mocks base method.
func (m *MockModelInterface) GetAttachmentByID(ctx context.Context, arg querier.GetAttachmentByIDParams) (*querier.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentByID", ctx, arg)
	ret0, _ := ret[0].(*querier.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentByID indicates an expected call of GetAttachmentByID.
func (mr *MockModelInterfaceMockRecorder) GetAttachmentByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentByID", reflect.TypeOf((*MockModelInterface)(nil).GetAttachmentByID), ctx, arg)
}

// GetCounter mocks base method.
func (m *MockModelInterface) GetCounter(ctx context.Context) (*querier.Counter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx)
	ret0, _ := ret[0].(*querier.Counter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockModelInterfaceMockRecorder) GetCounter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockModelInterface)(nil).GetCounter), ctx)
}

// GetDeviceCodeByDeviceHash mocks base method.
func (m *MockModelInterface) GetDeviceCodeByDeviceHash(ctx context.Context, deviceCodeHash []byte) (*querier.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCodeByDeviceHash", ctx, deviceCodeHash)
	ret0, _ := ret[0].(*querier.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceCodeByDeviceHash indicates an expected call of GetDeviceCodeByDeviceHash.
func (mr *MockModelInterfaceMockRecorder) GetDeviceCodeByDeviceHash(ctx, deviceCodeHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCodeByDeviceHash", reflect.TypeOf((*MockModelInterface)(nil).GetDeviceCodeByDeviceHash), ctx, deviceCodeHash)
}

// GetDeviceCodeByUserHash mocks base method.
func (m *MockModelInterface) GetDeviceCodeByUserHash(ctx context.Context, userCodeHash []byte) (*querier.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCodeByUserHash", ctx, userCodeHash)
	ret0, _ := ret[0].(*querier.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceCodeByUserHash indicates an expected call of GetDeviceCodeByUserHash.
func (mr *MockModelInterfaceMockRecorder) GetDeviceCodeByUserHash(ctx, userCodeHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCodeByUserHash", reflect.TypeOf((*MockModelInterface)(nil).GetDeviceCodeByUserHash), ctx, userCodeHash)
}

// GetMemoByID mocks base method.
func (m *MockModelInterface) GetMemoByID(ctx context.Context, arg querier.GetMemoByIDParams) (*querier.GetMemoByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoByID", ctx, arg)
	ret0, _ := ret[0].(*querier.GetMemoByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemoByID indicates an expected call of GetMemoByID.
func (mr *MockModelInterfaceMockRecorder) GetMemoByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoByID", reflect.TypeOf((*MockModelInterface)(nil).GetMemoByID), ctx, arg)
}

// InTransaction mocks base method.
func (m *MockModelInterface) InTransaction() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction")
	ret0, _ := ret[0].(bool)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockModelInterfaceMockRecorder) InTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*MockModelInterface)(nil).InTransaction))
}

// IncrementCounter mocks base method.
func (m *MockModelInterface) IncrementCounter(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCounter", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockModelInterfaceMockRecorder) IncrementCounter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockModelInterface)(nil).IncrementCounter), ctx)
}

// ListAttachmentsByResource mocks base method.
func (m *MockModelInterface) ListAttachmentsByResource(ctx context.Context, arg querier.ListAttachmentsByResourceParams) ([]*querier.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttachmentsByResource", ctx, arg)
	ret0, _ := ret[0].([]*querier.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttachmentsByResource indicates an expected call of ListAttachmentsByResource.
func (mr *MockModelInterfaceMockRecorder) ListAttachmentsByResource(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttachmentsByResource", reflect.TypeOf((*MockModelInterface)(nil).ListAttachmentsByResource), ctx, arg)
}

// ListMemoBacklinks mocks base method.
func (m *MockModelInterface) ListMemoBacklinks(ctx context.Context, arg querier.ListMemoBacklinksParams) ([]*querier.ListMemoBacklinksRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemoBacklinks", ctx, arg)
	ret0, _ := ret[0].([]*querier.ListMemoBacklinksRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemoBacklinks indicates an expected call of ListMemoBacklinks.
func (mr *MockModelInterfaceMockRecorder) ListMemoBacklinks(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemoBacklinks", reflect.TypeOf((*MockModelInterface)(nil).ListMemoBacklinks), ctx, arg)
}

// ListMemoReferenceIDsBySource mocks base method.
func (m *MockModelInterface) ListMemoReferenceIDsBySource(ctx context.Context, arg querier.ListMemoReferenceIDsBySourceParams) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemoReferenceIDsBySource", ctx, arg)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemoReferenceIDsBySource indicates an expected call of ListMemoReferenceIDsBySource.
func (mr *MockModelInterfaceMockRecorder) ListMemoReferenceIDsBySource(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemoReferenceIDsBySource", reflect.TypeOf((*MockModelInterface)(nil).ListMemoReferenceIDsBySource), ctx, arg)
}

// ListMemoTagsByMemo mocks base method.
func (m *MockModelInterface) ListMemoTagsByMemo(ctx context.Context, arg querier.ListMemoTagsByMemoParams) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemoTagsByMemo", ctx, arg)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemoTagsByMemo indicates an expected call of ListMemoTagsByMemo.
func (mr *MockModelInterfaceMockRecorder) ListMemoTagsByMemo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemoTagsByMemo", reflect.TypeOf((*MockModelInterface)(nil).ListMemoTagsByMemo), ctx, arg)
}

// ListMemos mocks base method.
func (m *MockModelInterface) ListMemos(ctx context.Context, arg querier.ListMemosParams) ([]*querier.ListMemosRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemos", ctx, arg)
	ret0, _ := ret[0].([]*querier.ListMemosRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemos indicates an expected call of ListMemos.
func (mr *MockModelInterfaceMockRecorder) ListMemos(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemos", reflect.TypeOf((*MockModelInterface)(nil).ListMemos), ctx, arg)
}

// ListTags mocks base method.
func (m *MockModelInterface) ListTags(ctx context.Context, arg querier.ListTagsParams) ([]*querier.ListTagsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx, arg)
	ret0, _ := ret[0].([]*querier.ListTagsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockModelInterfaceMockRecorder) ListTags(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockModelInterface)(nil).ListTags), ctx, arg)
}

// ListTodosByUser mocks base method.
func (m *MockModelInterface) ListTodosByUser(ctx context.Context, userID int32) ([]*querier.ListTodosByUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodosByUser", ctx, userID)
	ret0, _ := ret[0].([]*querier.ListTodosByUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTodosByUser indicates an expected call of ListTodosByUser.
func (mr *MockModelInterfaceMockRecorder) ListTodosByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodosByUser", reflect.TypeOf((*MockModelInterface)(nil).ListTodosByUser), ctx, userID)
}

// MarkDeviceCodeConsumed mocks base method.
func (m *MockModelInterface) MarkDeviceCodeConsumed(ctx context.Context, id int64) (*querier.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDeviceCodeConsumed", ctx, id)
	ret0, _ := ret[0].(*querier.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkDeviceCodeConsumed indicates an expected call of MarkDeviceCodeConsumed.
func (mr *MockModelInterfaceMockRecorder) MarkDeviceCodeConsumed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDeviceCodeConsumed", reflect.TypeOf((*MockModelInterface)(nil).MarkDeviceCodeConsumed), ctx, id)
}

// NormalizeTodayToWeek mocks base method.
func (m *MockModelInterface) NormalizeTodayToWeek(ctx context.Context, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizeTodayToWeek", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NormalizeTodayToWeek indicates an expected call of NormalizeTodayToWeek.
func (mr *MockModelInterfaceMockRecorder) NormalizeTodayToWeek(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizeTodayToWeek", reflect.TypeOf((*MockModelInterface)(nil).NormalizeTodayToWeek), ctx, userID)
}

// NormalizeWeekToLater mocks base method.
func (m *MockModelInterface) NormalizeWeekToLater(ctx context.Context, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizeWeekToLater", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NormalizeWeekToLater indicates an expected call of NormalizeWeekToLater.
func (mr *MockModelInterfaceMockRecorder) NormalizeWeekToLater(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizeWeekToLater", reflect.TypeOf((*MockModelInterface)(nil).NormalizeWeekToLater), ctx, userID)
}

// RunTransaction mocks base method.
func (m *MockModelInterface) RunTransaction(ctx context.Context, f func(ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockModelInterfaceMockRecorder) RunTransaction(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockModelInterface)(nil).RunTransaction), ctx, f)
}

// RunTransactionWithTx mocks base method.
func (m *MockModelInterface) RunTransactionWithTx(ctx context.Context, f func(pgx.Tx, ModelInterface) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransactionWithTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransactionWithTx indicates an expected call of RunTransactionWithTx.
func (mr *MockModelInterfaceMockRecorder) RunTransactionWithTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransactionWithTx", reflect.TypeOf((*MockModelInterface)(nil).RunTransactionWithTx), ctx, f)
}

// SpawnWithTx mocks base method.
func (m *MockModelInterface) SpawnWithTx(tx pgx.Tx) ModelInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnWithTx", tx)
	ret0, _ := ret[0].(ModelInterface)
	return ret0
}

// SpawnWithTx indicates an expected call of SpawnWithTx.
func (mr *MockModelInterfaceMockRecorder) SpawnWithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnWithTx", reflect.TypeOf((*MockModelInterface)(nil).SpawnWithTx), tx)
}

// TouchDeviceCodePoll mocks base method.
func (m *MockModelInterface) TouchDeviceCodePoll(ctx context.Context, id int64) (*querier.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchDeviceCodePoll", ctx, id)
	ret0, _ := ret[0].(*querier.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TouchDeviceCodePoll indicates an expected call of TouchDeviceCodePoll.
func (mr *MockModelInterfaceMockRecorder) TouchDeviceCodePoll(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchDeviceCodePoll", reflect.TypeOf((*MockModelInterface)(nil).TouchDeviceCodePoll), ctx, id)
}

// UpdateDeviceCodeStatus mocks base method.
func (m *MockModelInterface) UpdateDeviceCodeStatus(ctx context.Context, arg querier.UpdateDeviceCodeStatusParams) (*querier.DeviceCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceCodeStatus", ctx, arg)
	ret0, _ := ret[0].(*querier.DeviceCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeviceCodeStatus indicates an expected call of UpdateDeviceCodeStatus.
func (mr *MockModelInterfaceMockRecorder) UpdateDeviceCodeStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceCodeStatus", reflect.TypeOf((*MockModelInterface)(nil).UpdateDeviceCodeStatus), ctx, arg)
}

// UpdateMemo mocks base method.
func (m *MockModelInterface) UpdateMemo(ctx context.Context, arg querier.UpdateMemoParams) (*querier.UpdateMemoRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemo", ctx, arg)
	ret0, _ := ret[0].(*querier.UpdateMemoRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMemo indicates an expected call of UpdateMemo.
func (mr *MockModelInterfaceMockRecorder) UpdateMemo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemo", reflect.TypeOf((*MockModelInterface)(nil).UpdateMemo), ctx, arg)
}

// UpdateTodo mocks base method.
func (m *MockModelInterface) UpdateTodo(ctx context.Context, arg querier.UpdateTodoParams) (*querier.UpdateTodoRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", ctx, arg)
	ret0, _ := ret[0].(*querier.UpdateTodoRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockModelInterfaceMockRecorder) UpdateTodo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockModelInterface)(nil).UpdateTodo), ctx, arg)
}

// UpdateTodoBucket mocks base method.
func (m *MockModelInterface) UpdateTodoBucket(ctx context.Context, arg querier.UpdateTodoBucketParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodoBucket", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTodoBucket indicates an expected call of UpdateTodoBucket.
func (mr *MockModelInterfaceMockRecorder) UpdateTodoBucket(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodoBucket", reflect.TypeOf((*MockModelInterface)(nil).UpdateTodoBucket), ctx, arg)
}
