// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/wibus-wee/allinone/pkg"
	"github.com/wibus-wee/allinone/pkg/asynctask"
	"github.com/wibus-wee/allinone/pkg/config"
	"github.com/wibus-wee/allinone/pkg/handler"
	"github.com/wibus-wee/allinone/pkg/zcore/app"
	"github.com/wibus-wee/allinone/pkg/zcore/injection"
	"github.com/wibus-wee/allinone/pkg/zcore/model"
	"github.com/wibus-wee/allinone/pkg/zgen/taskgen"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	application, err := pkg.InitAnclaxApplication(configConfig)
	if err != nil {
		return nil, err
	}
	taskStoreInterface := injection.InjectTaskStore(application)
	taskRunner := taskgen.NewTaskRunner(taskStoreInterface)
	modelInterface, err := model.NewModel(configConfig, application)
	if err != nil {
		return nil, err
	}
	serverInterface, err := handler.NewHandler(modelInterface, taskRunner)
	if err != nil {
		return nil, err
	}
	authInterface := injection.InjectAuth(application)
	validator := handler.NewValidator(authInterface)
	executorInterface := asynctask.NewExecutor(modelInterface)
	taskHandler := taskgen.NewTaskHandler(executorInterface)
	plugin := app.NewPlugin(serverInterface, validator, taskHandler)
	appApp, err := pkg.Init(application, taskRunner, plugin, modelInterface)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}
