package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type multiValue []string

func (m *multiValue) String() string {
	return strings.Join(*m, ",")
}

func (m *multiValue) Set(value string) error {
	for _, part := range strings.Split(value, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		*m = append(*m, part)
	}
	return nil
}

func main() {
	in := flag.String("in", "api/v1.yaml", "input OpenAPI YAML file")
	out := flag.String("out", "api/todo.gen.yaml", "output subset YAML file")
	var prefixes multiValue
	flag.Var(&prefixes, "prefix", "path prefix to include; can be repeated or comma-separated")
	flag.Parse()
	if len(prefixes) == 0 {
		prefixes = multiValue{"/todos"}
	}

	data, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("read input %s: %v", *in, err)
	}

	var root map[string]any
	if err := yaml.Unmarshal(data, &root); err != nil {
		log.Fatalf("unmarshal input YAML: %v", err)
	}

	subset := make(map[string]any)
	for _, key := range []string{"openapi", "info", "servers"} {
		if v, ok := root[key]; ok {
			subset[key] = v
		}
	}

	pathsAny, ok := root["paths"]
	if !ok {
		log.Fatalf("input spec has no paths section")
	}

	paths, ok := pathsAny.(map[string]any)
	if !ok {
		log.Fatalf("paths is not an object in input spec")
	}

	subPaths := make(map[string]any)
	for p, v := range paths {
		if matchesAnyPrefix(p, prefixes) {
			subPaths[p] = v
		}
	}
	if len(subPaths) == 0 {
		log.Fatalf("no paths found with prefixes %q", []string(prefixes))
	}
	subset["paths"] = subPaths

	if comps, ok := root["components"]; ok {
		subset["components"] = comps
	}

	outData, err := yaml.Marshal(subset)
	if err != nil {
		log.Fatalf("marshal subset YAML: %v", err)
	}

	sortedPrefixes := append([]string(nil), prefixes...)
	sort.Strings(sortedPrefixes)

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Code generated by openapi-subset; DO NOT EDIT.")
	fmt.Fprintf(&buf, "# Source: %s\n", *in)
	fmt.Fprintf(&buf, "# Included paths with prefixes %q.\n\n", sortedPrefixes)
	buf.Write(outData)

	if err := os.WriteFile(*out, buf.Bytes(), 0o644); err != nil {
		log.Fatalf("write output %s: %v", *out, err)
	}
}

func matchesAnyPrefix(path string, prefixes []string) bool {
	for _, prefix := range prefixes {
		if strings.HasPrefix(path, prefix) {
			return true
		}
	}
	return false
}
