package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// Simple helper to derive a sub-spec from api/v1.yaml by path prefix.
// For now we:
//   - copy openapi/info/servers as-is
//   - keep only paths whose key starts with the given prefix (e.g. "/todos")
//   - copy components verbatim (can be pruned later if needed)
//
// This keeps v1.yaml as the single source of truth while producing
// smaller per-domain specs for other tooling.
func main() {
	in := flag.String("in", "api/v1.yaml", "input OpenAPI YAML file")
	out := flag.String("out", "api/todo.gen.yaml", "output subset YAML file")
	prefix := flag.String("prefix", "/todos", "path prefix to include")
	flag.Parse()

	data, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("read input %s: %v", *in, err)
	}

	var root map[string]any
	if err := yaml.Unmarshal(data, &root); err != nil {
		log.Fatalf("unmarshal input YAML: %v", err)
	}

	subset := make(map[string]any)

	// Preserve some top-level metadata.
	for _, key := range []string{"openapi", "info", "servers"} {
		if v, ok := root[key]; ok {
			subset[key] = v
		}
	}

	// Filter paths by prefix.
	pathsAny, ok := root["paths"]
	if !ok {
		log.Fatalf("input spec has no paths section")
	}

	paths, ok := pathsAny.(map[string]any)
	if !ok {
		log.Fatalf("paths is not an object in input spec")
	}

	subPaths := make(map[string]any)
	for p, v := range paths {
		if strings.HasPrefix(p, *prefix) {
			subPaths[p] = v
		}
	}

	if len(subPaths) == 0 {
		log.Fatalf("no paths found with prefix %q", *prefix)
	}

	subset["paths"] = subPaths

	// For now copy components wholesale. If we want a minimal spec later,
	// we can walk the kept paths, collect $ref targets, and prune components.
	if comps, ok := root["components"]; ok {
		subset["components"] = comps
	}

	outData, err := yaml.Marshal(subset)
	if err != nil {
		log.Fatalf("marshal subset YAML: %v", err)
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Code generated by openapi-subset; DO NOT EDIT.")
	fmt.Fprintf(&buf, "# Source: %s\n", *in)
	fmt.Fprintf(&buf, "# Included paths with prefix %q.\n\n", *prefix)
	buf.Write(outData)

	if err := os.WriteFile(*out, buf.Bytes(), 0o644); err != nil {
		log.Fatalf("write output %s: %v", *out, err)
	}
}
